### ISSUE TITLE
Error when trying to convert HEIC to JPG

### ISSUE THREAD

**Issue by alzawada** [major-mayer/imageconverter#1]
I have a nextcloud installed as linuxserver/nextcloud docker.
This docker already meet your requirements: HEIC support installed and the PHP bindings (Imagick extension) enabled,

In Nextcloud, when clicking on heic and trying to convert it i'm getting message: **_Error An Error occured!_**

Version of nextcloud: 18.0.6

**Comment by major-mayer** [comment]
Could you take a look in the network tab and copy the response from the "/convert" request?
Maybe there is a hint what is going wrong...

This is what i looks in Firefox (when everything works):
![grafik](https://user-images.githubusercontent.com/17907799/85949830-45a6ab00-b959-11ea-8c4e-7684af178649.png)

**Comment by alzawada** [comment]
Below you can find the message: 

{error: "Imagick failed to convert the images, check if you fulfill all requirements.",…}
details: "Invalid input: No 'ftyp' box `/tmp/magick-16665vZDGSDjfpaIB' @ error/heic.c/IsHeifSuccess/136"
error: "Imagick failed to convert the images, check if you fulfill all requirements."

**Comment by major-mayer** [comment]
Puh good question what's going on here.
It seems to be an error inside the imageMagic binary, but to be honest I don't have any idea what this error ("no ftyp box") means.
My Google-Foo didn't help either, I don't find other mentions of this error.

You could try to analyse the stack tree and find at which point in the imageConverter addon this error happens.
If you find the reason, tell me more and I will try to fix it.

**Comment by major-mayer** [comment]
I will close this for now, feel free to reopen if you gather additional information
