### ISSUE TITLE
v2.0.0 can not be enabled

### ISSUE THREAD

**Issue by bcutter** [major-mayer/imageconverter#14]
After updating to v2.0.0 and when trying to enable the app, I get
![grafik](https://github.com/major-mayer/imageconverter/assets/13799156/2485a679-e375-4db7-918c-3e79c859dbe3)

```
[PHP] Fehler: Class OCA\ImageConverter\AppInfo\Application contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\AppFramework\Bootstrap\IBootstrap::boot) at /var/www/nextcloud/apps/imageconverter/lib/AppInfo/Application.php#17
	POST /index.phpapps/enable
	von xxx.xxx.xxx.xxx von username um 05.04.2024, 20:52:09
```

This is logged every time clicking "Activate". Outcome with occ command not tested, likely the same :-(

**Comment by ninjazan420** [comment]
same, bricked my installation
changing the folder name to `imageconverter_` fixed it

just sh*t in my pants. :)

**Comment by SageSphinx63920** [comment]
Can confirm

**Comment by SageSphinx63920** [comment]
occ output:
```
root@gve-cloud:/var/www/nextcloud# sudo -u www-data php -f ./occ
PHP Fatal error:  Class OCA\ImageConverter\AppInfo\Application contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\AppFramework\Bootstrap\IBootstrap::boot) in /var/www/nextcloud/apps/imageconverter/lib/AppInfo/Application.php on line 17
{"reqId":"kJG5VzJ1xqbxJK8OZw0P","level":3,"time":"2024-04-05T22:09:29+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Class OCA\\ImageConverter\\AppInfo\\Application contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\AppFramework\\Bootstrap\\IBootstrap::boot) at /var/www/nextcloud/apps/imageconverter/lib/AppInfo/Application.php#17","userAgent":"--","version":"28.0.4.1","data":{"app":"PHP"}}```

**Comment by SageSphinx63920** [comment]
Further investigation shows that the `boot` method needed by IBootstrap is missing.

https://docs.nextcloud.com/server/latest/developer_manual/app_development/bootstrap.html#id2
https://docs.nextcloud.com/server/latest/developer_manual/app_development/bootstrap.html#booting-an-app

**Comment by ninjazan420** [comment]
> Can confirm. My instance if not even accessible from now on getting a 500 HTTP code.

hotfix is to go to
`/apps/` rename `imageconverter ` to `imageconverter_` and you should go to go if needed :)

**Comment by major-mayer** [comment]
Hey guys, sorry for the inconvenience. 
I accidentally deleted this boot method, because it contained no logic anyway.
Somehow, I missed that it is a (abstract?) method required by the IBootstrap interface and did my last tests with a version before I deleted it. Lesson learned ...

I added it again in 2.0.1, and now you should be able to enable the app again.

**Comment by bcutter** [comment]
Yes great it is working again. Thanks a lot :-)

**Comment by bcutter** [comment]
Yes great it is working again. Thanks a lot :-)
