### ISSUE TITLE
Massive log spam

### ISSUE THREAD

**Issue by TheColin21** [major-mayer/imageconverter#3]
{"reqId":"X-LOoSrdRvqppRN6gPdNXAAAAFg","level":3,"time":"2021-01-04T08:15:29+00:00","remoteAddr":"37.247.74.58","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/logreader/poll?lastReqId=X-LOoSrdRvqppRN6gPdNWwAAAEQ","message":{"Exception":"Error","Message":"include_once(): Failed opening '/var/www/vhosts/path/to.my.cloud/apps/imageconverter/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/vhosts/path/to.my.cloud/3rdparty/pear/archive_tar:/var/www/vhosts/path/to.my.cloud/3rdparty/pear/console_getopt:/var/www/vhosts/path/to.my.cloud/3rdparty/pear/pear-core-minimal/src:/var/www/vhosts/path/to.my.cloud/3rdparty/pear/pear_exception:/var/www/vhosts/path/to.my.cloud/apps') at /var/www/vhosts/path/to.my.cloud/apps/imageconverter/lib/AppInfo/Application.php#37","Code":0,"Trace":[{"file":"/var/www/vhosts/path/to.my.cloud/apps/imageconverter/lib/AppInfo/Application.php","line":37,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/vhosts/path/to.my.cloud/apps/imageconverter/lib/AppInfo/Application.php","line":37,"function":"include_once"},{"file":"/var/www/vhosts/path/to.my.cloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"register","class":"OCA\\ImageConverter\\AppInfo\\Application","type":"->"},{"file":"/var/www/vhosts/path/to.my.cloud/lib/base.php","line":644,"function":"runRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/vhosts/path/to.my.cloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/var/www/vhosts/path/to.my.cloud/index.php","line":35,"args":["/var/www/vhosts/path/to.my.cloud/lib/base.php"],"function":"require_once"}],"File":"/var/www/vhosts/path/to.my.cloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0","id":"5ff2cea174960"}

this error gets spammed every second since last update, even after removing and reinstalling the app

Ubuntu 20.04 on KVM with Plesk and PHP 7.4

**Comment by major-mayer** [comment]
Thanks for the fast report.
Seems like i've forgotten to remove a line from the IBootstrap guide, thats leads to an import of an non existing file.
I will release the update very soon!

**Comment by TheColin21** [comment]
Thanks, could you please mention it in this issue so I can enable the app again?

Am 4. Januar 2021 09:49:05 MEZ schrieb major-mayer <notifications@github.com>:

**Comment by major-mayer** [comment]
I've just updated it, but i don't know how long it takes for Nextcloud to distribute the app release.
Here you can download it manually if you don't want to wait: https://github.com/major-mayer/imageconverter/releases/download/v.1.3.1/imageconverter.tar.gz
