### ISSUE TITLE
Server error: 503 Service Unavailable

### ISSUE THREAD

**Issue by Chenxin0007** [major-mayer/imageconverter#6]
Server error: `GET https://github.com/major-mayer/imageconverter/releases/download/v.1.3.2/imageconverter.tar.gz` resulted in a `503 Service Unavailable` response: <!DOCTYPE html> <!-- Hello future GitHubber! I bet you're here to remove those nasty inline styles, DRY up these te (truncated...)

**Comment by major-mayer** [comment]
Are you sure about that?
For me this link works just fine: https://github.com/major-mayer/imageconverter/releases/download/v.1.3.2/imageconverter.tar.gz

Maybe it was a temporary GitHub outage? Please double check it

**Comment by major-mayer** [comment]
Closing this as it seems to be stale
