### ISSUE TITLE
NC 24 Support

### ISSUE THREAD

**Issue by Pablo1732** [major-mayer/imageconverter#7]
Please add Official Support for Nextcloud Version 24

**Comment by major-mayer** [comment]
Sorry for the huge delay.
I had big problems getting my development setup back running, and I wanted to do at least some testing before publishing a new version to the app store.
There were no incompatibilities that I could find, neither in the docs nor by actual converting. 
So seems to be good to go for NC 24/25 :slightly_smiling_face: 

Please report if you find any issues.
