### ISSUE TITLE
Nextcloud 23.03 - cannot open images in HEIC Format

### ISSUE THREAD

**Issue by Githopp192** [major-mayer/imageconverter#8]
### Actual behaviour

i can see/open all photos in HEIC Format, taken from iPhone 7, but all photos in HEIC Format, taken from iPhone XS, users are not able to view it.

### Steps to reproduce

whenever i'm trying to open a *.heic photo from newer iPhones

### Expected behaviour

users should be able to view the image

### --------------------------------
iPhone XS

### --------------------------------

Version: Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz
Max Speed    : 4300 MHz
Current Speed: 3300 MHz
Memory: 7.58GB
----------------------------------------------

Operating System:  Red Hat Enterprise Linux release 8.5 (Ootpa)

Webserver:  Apache/2.4.37 (Red 

Database:  mysql 10.3.28-MariaDB,

PHP version:  PHP Version => 7.4.26

Nextcloud:    - version: 23.0.3.2
### Updated from an older Nextcloud/ownCloud or fresh install:
Update from older nc

### Where did you install Nextcloud from:

origin source

### Signing status:

Login as admin user into your Nextcloud and access http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.

**Comment by major-mayer** [comment]
Are you sure you are using this app? If not, this should be posted to @nextcloud/server 
If yes, what are the steps to reproduce the issue?
Can you upload some photos that you can't convert successful?

**Comment by Githopp192** [comment]
yes, used/tried both - access by server, access by app

1. choose file, double-click

![ScreenShot075](https://user-images.githubusercontent.com/32612067/185778775-57f3588b-1a2a-45cd-8ee0-61714c67c3d6.jpg)

2. error 

![ScreenShot074](https://user-images.githubusercontent.com/32612067/185778800-feb00cd8-c913-4172-8aad-5b18bbb4237f.jpg)

3. trying to convert the file

![ScreenShot076](https://user-images.githubusercontent.com/32612067/185778822-1277086b-2b09-4715-b679-6b4426e7a663.jpg)

4. error converting

![ScreenShot077](https://user-images.githubusercontent.com/32612067/185778841-4b40b101-f8a4-42c3-885a-1bad34f52c0b.jpg)

and is the zipped FILE:

[TEST.zip](https://github.com/major-mayer/imageconverter/files/9388618/TEST.zip)

**Comment by Githopp192** [comment]
Details of heic format taken from iPhone 7: no issues at all

![20220820_125823](https://user-images.githubusercontent.com/32612067/185786918-2e7d6a2b-fe37-4721-a876-fbb42c33f959.png)

Details of heic format taken from iPhone XS: issues 
![20220820_125930](https://user-images.githubusercontent.com/32612067/185786939-f04e0295-13fb-4bb8-ae3d-2b2d16df580d.png)

**Comment by major-mayer** [comment]
Hmm I cannot reproduce this on my end.
I was able to open the HEIC file normally, as you also could, but I was also able to convert this image with the imageconverter app without any problems.

However I noticed that when i try to convert this image, I get the following log entry that doesn't happen when I convert other images:
```
{"reqId":"xeuzFQ3uamw3PojAN0FA","level":3,"time":"2022-10-17T21:43:03+00:00","remoteAddr":"172.25.0.1","user":"admin","app":"PHP","method":"POST","url":"/apps/imageconverter/convert","message":"exif_read_data(): Incorrect APP1 Exif Identifier Code at /var/www/nextcloud/lib/private/Metadata/Provider/ExifProvider.php#20","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0","version":"25.0.0.17","exception":{"Exception":"Error","Message":"exif_read_data(): Incorrect APP1 Exif Identifier Code at /var/www/nextcloud/lib/private/Metadata/Provider/ExifProvider.php#20","Code":0 [...]}}
```
So maybe ImageMagick doesn't like something about your HEIC image, but i don't exactly know what "Incorrect APP1 Exif Identifier Code" means.

Can you maybe post your Nextcloud logs searching for imageconverter?

**Comment by major-mayer** [comment]
I have just pushed a new version that logs errors in the Nextcloud logs and also in the browser console (if the server's response reaches the browser).

**Comment by major-mayer** [comment]
I will close this issue due to inactivity.
If you still experience this error, please open a new issue.
